subview interactive dismiss lag
nathantannar4/InputBarAccessoryView pull request #151
Opened 2020-09-16 23:40 UTC by AndrewSB

patch-2

2020-09-16 23:42 UTC, AndrewSB commented
The first commit in here is from #148.  That needs to be merged before this does

2020-10-19 12:07 UTC, Kaspik requested changes

2020-10-19 12:07 UTC, Kaspik commented on Sources/KeyboardManager/KeyboardManager.swift
> +    private var tabBarHeight: CGFloat?
remove

2020-10-19 12:07 UTC, Kaspik commented on Sources/KeyboardManager/KeyboardManager.swift
> +        let yCoordinateDirectlyAboveKeyboard = -frame.height + (self.tabBarHeight ?? 0)
get rid of tabBarHeight

2020-10-22 10:47 UTC, Kaspik commented
Please update this PR so we can merge the animation lag fix. :)

2021-03-06 00:46 UTC, AndrewSB commented
updated and rebased!

2021-03-07 15:34 UTC, Kaspik approved these changes
Ideally add changelog entry please :)

2021-03-07 15:35 UTC, merged