feat: key commands for external keyboards
nathantannar4/InputBarAccessoryView pull request #243
Opened 2023-04-16 07:13 UTC by nathanwhy

What does this implement/fix? Explain your changes.
---------------------------------------------------
Support for external keyboard to send messages by pressing command + enter.
On the Mac catalyst, it also supports keyboard shortcuts.

Does this close any currently open issues?
------------------------------------------
No

Where has this been tested?
---------------------------
**Devices/Simulators:** …
iPad mini 6
**iOS Version:** …
iOS 16.2
**Swift Version:** …
5.7

How to use:
```
messageInputBar.inputTextView.observeKeyInput("\r", modifiers: .command, discoverabilityTitle: nil) {
    // send message with command + enter
}
```

2023-05-23 13:41 UTC, Kaspik requested changes

2023-05-23 13:41 UTC, Kaspik commented on Sources/Views/InputTextView.swift
> +        let key = "\(String(describing: keyCommand.input!))_\(keyCommand.modifierFlags)"
Not a big fan of this force unwrap - can we figure out better way for the key?

2023-05-24 19:37 UTC, Janneman84 commented
In my app I made it so pressing physical return key sends message and shift+return adds a new line. I believe this is how other apps work too.

If interested I can show code how I achieved this.

2023-06-16 06:14 UTC, nathanwhy commented
@Janneman84 can you show me how to achieved it?

2023-06-16 22:38 UTC, Janneman84 commented
> @Janneman84 can you show me how to achieved it?

```
extension InputTextView {
    
    open override var keyCommands: [UIKeyCommand]? {
        return [
            //hitting return on hardware keyboard will send the message instead of carriage return
            //to go to next line press shift+return
            UIKeyCommand(input: "\r", modifierFlags: [], action: #selector(keyCommand_return)),
        ]
    }
    
    @objc private func keyCommand_return() {
        //trigger send press here
    }
}
```
I use an extension but you can probably implement the override directly in InputTextView. 

However if you plan on it calling `didPressSendButtonWith` I would need to know wether this is triggered through button touch or keyboard return press. This because my send button is the photo button when there is no text entered. It opens the camera when pressed, but I don't want it to open the camera when you hit return on the keyboard. Hence I need to be able to make the distinction.

2024-06-28 23:06 UTC, nathantannar4 requested changes

2024-06-28 23:06 UTC, nathantannar4 commented on Sources/KeyboardManager/KeyboardManager.swift
> -            guard notification.isForCurrentApp else { return }
What's the reason for removing this?

2024-06-28 23:06 UTC, nathantannar4 commented on Sources/InputBarAccessoryView.swift
> +    open var textViewHeightAnchor: NSLayoutConstraint?
Unintentional change as well?

2025-09-02 06:22 UTC, closed without merging