fixes layout issues on iPad pagesheets (issue #238)
nathantannar4/InputBarAccessoryView pull request #244
Opened 2023-05-23 10:17 UTC by Janneman84

What does this implement/fix? Explain your changes.
---------------------------------------------------
This fixes layout (gap) issues when keyboard appears on iPad when VC is presented as pagesheet of formsheet.

Does this close any currently open issues?
------------------------------------------
This fixes issue #238

Any relevant logs, error output, etc?
-------------------------------------
none

Any other comments?
-------------------
The fixes are a bit hacky but it's the only way I could find that works.

Where has this been tested?
---------------------------
**Devices/Simulators:** 
iPad with and without home button, also tested on various iPhones to make sure it kept working fine there too.

**iOS Version:** 
14/15/16

**Swift Version:** 
the one used by Xcode 14.3

**InputBarAccessoryView Version:** 
6.2.0

2023-05-23 13:39 UTC, Kaspik requested changes

2023-05-23 21:59 UTC, Janneman84 commented
I pushed some tweaks to the master branche. Can you see it?

The reason for starting the animation a second time inside dispatchqueue is because on iPad in portrait when the keyboard slides in the pagesheet will move up a little too. So you need to wait a cycle to get te correct compensation value or else you'll still have a gap.

2023-05-23 22:10 UTC, Kaspik approved these changes

2023-05-23 22:10 UTC, Kaspik commented
Add info to the Changelog please. :)

2023-05-24 10:23 UTC, Janneman84 commented
I added a line to the changelog.

I also did some code optimizations to prevent unnecessary calling of `animateAlongside()`. Works fine as far as I tested :P.

2023-05-24 17:33 UTC, Kaspik approved these changes

2023-05-24 17:37 UTC, merged